# Generated by Django 2.1.2 on 2018-11-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcartapp', '0013_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
