# Generated by Django 2.1.2 on 2018-11-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcartapp', '0018_comment_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
