# Generated by Django 2.1.2 on 2018-11-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcartapp', '0019_auto_20181127_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
