# Generated by Django 2.1.2 on 2018-11-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcartapp', '0024_auto_20181128_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
