# Generated by Django 2.1.2 on 2018-11-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcartapp', '0027_auto_20181128_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
